# -*- coding: utf-8 -*-
"""Ejercicio 4.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsXEugAtpi5ISqvHFIbtUpl-UjhJkCqn
"""

class Profesor:
    """Clase base que representa un profesor genérico."""
    def imprimir(self):
        print("Es un profesor.")

class ProfesorTitular(Profesor):
    """Clase derivada que representa un profesor titular."""
    def imprimir(self):
        print("Es un profesor titular.")

def main():
    profesor1 = ProfesorTitular()
    profesor1.imprimir()

if __name__ == "__main__":
    main()