# -*- coding: utf-8 -*-
"""Ejercicio 4.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3uKdANTdMXn7f3oASYWFIUbaKzXIokV
"""

class Inmueble:
    def __init__(self, id_inmobiliario, area, direccion):
        self.id_inmobiliario = id_inmobiliario
        self.area = area
        self.direccion = direccion

    def imprimir(self):
        print(f"ID: {self.id_inmobiliario}, Área: {self.area}, Dirección: {self.direccion}")


class InmuebleVivienda(Inmueble):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos):
        super().__init__(id_inmobiliario, area, direccion)
        self.habitaciones = habitaciones
        self.banos = banos

    def imprimir(self):
        super().imprimir()
        print(f"Habitaciones: {self.habitaciones}, Baños: {self.banos}")


class Casa(InmuebleVivienda):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos, pisos):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos)
        self.pisos = pisos

    def imprimir(self):
        super().imprimir()
        print(f"Pisos: {self.pisos}")


class CasaRural(Casa):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos, pisos, distancia, altitud):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos, pisos)
        self.distancia = distancia
        self.altitud = altitud

    def imprimir(self):
        super().imprimir()
        print(f"Distancia a cabecera: {self.distancia} km, Altitud: {self.altitud} m")


class CasaUrbana(Casa):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos, pisos, tipo):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos, pisos)
        self.tipo = tipo

    def imprimir(self):
        super().imprimir()
        print(f"Tipo: {self.tipo}")


class CasaConjuntoCerrado(CasaUrbana):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos, pisos, admin, areas_comunes):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos, pisos, "Conjunto Cerrado")
        self.admin = admin
        self.areas_comunes = areas_comunes

    def imprimir(self):
        super().imprimir()
        print(f"Valor administración: ${self.admin}, Áreas comunes: {'Sí' if self.areas_comunes else 'No'}")


class CasaIndependiente(CasaUrbana):
    def __init__(self, id_inmobiliario, area, direccion, habitaciones, banos, pisos):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos, pisos, "Independiente")


class Apartamento(InmuebleVivienda):
    def __init__(self, id_inmobiliario, area, direccion, precio_venta, habitaciones, banos, admin=None):
        super().__init__(id_inmobiliario, area, direccion, habitaciones, banos)
        self.precio_venta = precio_venta
        self.admin = admin

    def imprimir(self):
        print("Datos apartamento")
        print(f"Identificador inmobiliario = {self.id_inmobiliario}")
        print(f"Area = {self.area}")
        print(f"Dirección = {self.direccion}")

        print(f"Precio de venta = ${self.precio_venta:.1E}")
        print(f"Número de habitaciones = {self.habitaciones}")
        print(f"Número de baños = {self.banos}")
        if self.admin is not None:
            print(f"Valor de la administración = ${int(self.admin)}")
        print()


class Apartaestudio(Apartamento):
    def __init__(self, id_inmobiliario, area, direccion, precio_venta, banos, admin):

        super().__init__(id_inmobiliario, area, direccion, precio_venta, 1, banos, admin)


class ApartamentoFamiliar(Apartamento):
    def __init__(self, id_inmobiliario, area, direccion, precio_venta, habitaciones, banos, admin):
        super().__init__(id_inmobiliario, area, direccion, precio_venta, habitaciones, banos, admin)


class Local(Inmueble):
    def __init__(self, id_inmobiliario, area, direccion, ubicacion):
        super().__init__(id_inmobiliario, area, direccion)
        self.ubicacion = ubicacion

    def imprimir(self):
        super().imprimir()
        print(f"Ubicación: {self.ubicacion}")


class LocalComercial(Local):
    def __init__(self, id_inmobiliario, area, direccion, ubicacion, centro_comercial):
        super().__init__(id_inmobiliario, area, direccion, ubicacion)
        self.centro_comercial = centro_comercial

    def imprimir(self):
        super().imprimir()
        print(f"Centro Comercial: {self.centro_comercial}")


class Oficina(Local):
    def __init__(self, id_inmobiliario, area, direccion, ubicacion, es_gobierno):
        super().__init__(id_inmobiliario, area, direccion, ubicacion)
        self.es_gobierno = es_gobierno

    def imprimir(self):
        super().imprimir()
        print(f"Es del gobierno: {'Sí' if self.es_gobierno else 'No'}")


if __name__ == "__main__":
    # Creamos los dos apartamentos EXACTAMENTE como en la figura 4.6:
    ap1 = Apartamento(
        103067,             # ID
        120,                # Área
        "Avenida Santander 45-45",
        2.4e8,              # Precio de venta
        3,                  # Habitaciones
        2,                  # Baños
        admin=200000        # Administración
    )

    ap2 = Apartamento(
        12354,
        50,
        "Avenida Caracas 30-15",
        7.5e7,
        1,
        1,
        admin=None         # Sin administración
    )

    ap1.imprimir()
    ap2.imprimir()