# -*- coding: utf-8 -*-
"""Actividad 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrUogLJX5dUT3ADjQjymgsGo1KnPMH0C

Ejercicio 4.1 página 194
"""

class Cuenta:
    def __init__(self, saldo_inicial: float, tasa_anual: float):
        self.saldo = saldo_inicial
        self.num_consignaciones = 0
        self.num_retiros = 0
        self.tasa_anual = tasa_anual
        self.comision_mensual = 0.0

    def consignar(self, monto: float) -> None:
        self.saldo += monto
        self.num_consignaciones += 1

    def retirar(self, monto: float) -> None:
        if monto <= self.saldo:
            self.saldo -= monto
            self.num_retiros += 1
        else:
            print(f"Saldo insuficiente para retiro de {monto:.2f}")

    def calcular_interes(self) -> None:
        interes_mensual = (self.tasa_anual / 12) * self.saldo
        self.saldo += interes_mensual

    def extracto_mensual(self) -> None:
        self.saldo -= self.comision_mensual
        self.calcular_interes()
        # reiniciar
        self.num_consignaciones = 0
        self.num_retiros = 0
        self.comision_mensual = 0.0

class CuentaAhorros(Cuenta):
    def __init__(self, saldo_inicial: float, tasa_anual: float):
        super().__init__(saldo_inicial, tasa_anual)
        self.activa = self.saldo >= 10000

    def consignar(self, monto: float) -> None:
        if self.activa:
            super().consignar(monto)

    def retirar(self, monto: float) -> None:
        if self.activa:
            super().retirar(monto)
            if self.num_retiros > 4:
                self.comision_mensual += 1000

if __name__ == "__main__":
    print("Cuenta de ahorros")
    saldo_inicial = float(input("Ingrese saldo inicial= $").replace(",", "."))
    tasa_anual    = float(input("Ingrese tasa de interés= ").replace(",", "."))
    monto_cons    = float(input("Ingresar cantidad a consignar: $").replace(",", "."))
    monto_ret     = float(input("Ingresar cantidad a retirar: $").replace(",", "."))

    cuenta = CuentaAhorros(saldo_inicial, tasa_anual)
    cuenta.consignar(monto_cons)
    cuenta.retirar(monto_ret)

    transacciones = cuenta.num_consignaciones + cuenta.num_retiros

    cuenta.extracto_mensual()

    print(f"Saldo = $ {cuenta.saldo:.6f}")
    print(f"Comisión mensual = $ {cuenta.comision_mensual:.1f}")
    print(f"Número de transacciones = {transacciones}")
